Fix problems related to JDK 11
When testing on a machine that has JDK 11 installed, we came across two problems in the codebase related to things that were no longer supported.

1. Redundant import in the code that caused problems
2. JAXB no longer part of base Java and must be included manually via pom.xml

1. Simply remove the import
2. See [SO-post](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)